### ISSUE TITLE
DTE1 Create project

### ISSUE THREAD

**Issue by esalasl** [esalasl/DII2425TPVEspartanos#2]
Crear proyecto ReactNative llamado DII2425TPVEspartanos y decidid si crearlo a través de Expo o CLI

Subirlo al repo al que os he invitado

**Comment by CristianRodrigorc** [comment]
![Image](https://github.com/user-attachments/assets/da9c2613-46d9-4967-bf5e-1be378e353f0)

**Comment by YLJOSE** [comment]
DII2425TPVEspartanos - creación de proyecto culminado
