### ISSUE TITLE
DTE2 Configure Local Project

### ISSUE THREAD

**Issue by esalasl** [esalasl/DII2425TPVEspartanos#3]
Terminad de configurar el entorno, clonando el projecto.

Comprobar que la simulación funciona correctamente.

**Comment by CristianRodrigorc** [comment]
![Image](https://github.com/user-attachments/assets/360ceef0-21a0-41e4-b662-21c5df0591b4)
![Image](https://github.com/user-attachments/assets/a79c014b-479c-4bf7-96d8-9476039aac03)
