### ISSUE TITLE
DTE4 Crear Pantalla Inicial y Manejo de estados

### ISSUE THREAD

**Issue by esalasl** [esalasl/DII2425TPVEspartanos#5]
Crear Pantalla inicial con una lista de botones de mesa:
- El botón de mesa tiene que ser un componente
- La Pantalla inicial tiene que ser un componente

Manejar estado en el contenedor principal para el manejo transiciones de vista actual, de cada mesa se mostrará una pantalla vacía

![Image](https://github.com/user-attachments/assets/a82239c8-5290-4f59-9fde-ffec590c649a)

**Comment by CristianRodrigorc** [comment]
Se realizó la pantalla inicial y el método el cambio de ventanas
