### ISSUE TITLE
DTE5 Crear vistas de opciones de mesa

### ISSUE THREAD

**Issue by esalasl** [esalasl/DII2425TPVEspartanos#6]
Crear la vista de opciones de mesa con una lista de botones de opción.

- El botón de opción debe ser un componente
- la vista de opciones de mesa debe ser un componente

Actualizar Tarea tras DTC4, actualizando estado de vista actual

![Image](https://github.com/user-attachments/assets/400c10ff-c721-4b6b-979e-40eabf8ffe23)

**Comment by YLJOSE** [comment]
![task](https://github.com/user-attachments/assets/b3dd702b-4a56-42d7-b294-7b10cf535905)

**Comment by esalasl** [comment]
@YLJOSE antes de terminar, debes crear la PR https://github.com/esalasl/DII2425TPVEspartanos/pull/7
y esperar a que sea revisada y se apruebe y mergee.

Ten en cuenta que luego, cuando se termine la DTE4 ( o bien coordinado por Cristian ) se deberá integrar el estado que mostrar o no esta pantalla
